import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/DanySK/alchemist-incarnation-protelis
     */
    const val alchemist_incarnation_protelis: String =
            "it.unibo.alchemist:alchemist-incarnation-protelis:" + Versions.it_unibo_alchemist

    /**
     * https://github.com/DanySK/alchemist-loading
     */
    const val alchemist_loading: String = "it.unibo.alchemist:alchemist-loading:" +
            Versions.it_unibo_alchemist

    /**
     * https://github.com/DanySK/alchemist-runner
     */
    const val alchemist_runner: String = "it.unibo.alchemist:alchemist-runner:" +
            Versions.it_unibo_alchemist

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin
}
